server:
  port: 8888

eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8761/eureka
      defaultZone: http://eureka.c:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      # - id: employeeModule
      #   uri: lb://FIRST-SERVICE
      #   predicates:
      #   - Path=/employee/**
        
      # - id: consumerModule
      #   uri: lb://SECOND-SERVICE
      #   predicates:
      #   - Path=/consumer/**

      - id: cookbookAPI
        uri: lb://COOKBOOKAPI        
        predicates:
        - Path=/cookbook/**        
        #you can now hit this api gateway via: http://localhost:8888/api1/abc

      - id: recipeAPI
        uri: lb://RECIPEAPI
        predicates:
        - Path=/recipe/**
        #you can now hit endpoint like: http://localhost:8888/test1 this somehow maps to the minimal api endpoints

      - id: userAPI
        uri: lb://USERAPI
        predicates:
        - Path=/user/**
        #you can now hit http://localhost:8888/api2